force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Customer Contact)</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Doctor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor Contact)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status denoting if the Appointment is accepted or not by the doctor</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AppointmentContact__c/AppointmentContact__c.object-meta.xml
<CustomObject>
    <label>AppointmentContact</label>
    <nameField>
        <displayFormat>AppointmentContact-{0000}</displayFormat>
        <label>AppointmentContact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppointmentContacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AppointmentContact__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>AppointmentContacts</relationshipLabel>
    <relationshipName>AppointmentContacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residence</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This is the custom record type for the Customer profile.  It hides custom Doctor picklists.</description>
    <label>Customer</label>
       

</RecordType>

force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <description>Place where Doctor can hold Appointments</description>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {

    public static void createData(){
        List<Appointment__c> appList = new List<Appointment__c>();
        List<AppointmentContact__c> aconList = new List<AppointmentContact__c>();
        List<Contact> conList = new List<Contact>();
        List<Residence__c> resList = new List<Residence__c>();
        List<Account> testAccts = new List<Account>();

        //Accounts 
        testAccts.add(new Account(Name='Helloworld'));
        
        String recTypeDoc = Schema.SObjectType.Contact.getRecordTypeInfosByName()
                  .get('Doctor').getRecordTypeId();
        String recTypeCust = Schema.SObjectType.Contact.getRecordTypeInfosByName()
                  .get('Customer').getRecordTypeId();  
        //Contacts
        for(Integer i = 0 ; i < 20; i++)
        {
            Contact obj = new Contact();
        
            if(i < 10)
            { 
                obj.AccountId = testAccts.get( 0 ).id;
                obj.LastName = 'Last'+i;
                obj.recordTypeId = recTypeDoc;
            }
            if(i >= 10)
            {
                obj.AccountId = testAccts.get( 0 ).id;
                obj.LastName = 'Last'+i;
                obj.recordTypeId = recTypeCust;
            }
            obj.Gender__c = (0 == Math.mod( i , 2 ) ? 'Female': 'Male');
            conList.add(obj);
        }
       

        //Appointments
        for(Integer j = 0; j < 10; j++)
        {
                appList.add(new Appointment__c(Status__c = 'Pending',
                                               Start_Time__c = DateTime.now().addDays(j),
                                               Customer_Contact__c = conList.get( 10 ).Id,
                                               Doctor_Contact__c = conList.get( 0 ).Id));
        }

        try 
        {
            insert testAccts;
            insert conList;
            insert appList;
            
        } catch (DmlException dme) 
        {
            System.debug(dme.getMessage());
        }
        
    }
}