force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Customer Contact)</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Doctor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor Contact)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status denoting if the Appointment is accepted or not by the doctor</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Cherokee</fullName>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This is the custom record type for the Customer profile.  It hides custom Doctor picklists.</description>
    <label>Customer</label>
       

</RecordType>

force-app/main/default/classes/TestLAC_CustomerController.cls
@IsTest
public with sharing class TestLAC_CustomerController 
{
    @IsTest (seeAllData=true)
    static public void runTest() 
    {	
        System.debug( LAC_CustomerController.getDoctors('any', 'any', 'any') );
     	System.debug( LAC_CustomerController.getDoctors('Anesthesiology', 'Male', 'English') );
        
        String userFullName = UserInfo.getName();
        Contact customer = database.query('Select Id, Name, Email, Phone From Contact Where Name=:userFullName Limit 1');
        System.AssertEquals( LAC_CustomerController.getCustomerInfo(), customer );
        
        User u = [ SELECT Id, ContactId FROM User WHERE id =: userInfo.getUserId()];
        Contact cust = [ SELECT Id FROM Contact WHERE id =: u.ContactId ];
        List<Appointment__c> appList = database.query('SELECT Id, Start_Time__c, Message__c, Status__c, Doctor_Contact__r.Id, Doctor_Contact__r.Name FROM Appointment__c WHERE Customer_Contact__c = :cust.Id Limit 1');
        System.AssertEquals(LAC_CustomerController.getCustomerAppts(), appList);
        
        List<String> genders = new List<String>{};
           	genders.add('Any');
        	genders.add('Male');
        	genders.add('Female');
        	genders.add('Other');
        	
            
        
        List<String> languages = new List<String>{};
            for ( PicklistEntry lang : 	Contact.Languages__c.getDescribe().getPicklistValues() ) {
                languages.add( lang.getLabel() );
            }
        	languages.add('Any');
        
        List<String> specialities = new List<String>{};
        	specialities.add('Any');
        	specialities.add('Immunology');
        	specialities.add('Anesthesiology');
        	specialities.add('Dermatology');
        	specialities.add('Neurology');
        	specialities.add('Ophthalmology');
        	specialities.add('Pathology');
        	specialities.add('Psychiatry');
        	specialities.add('Urology');
        
        
        
        
        
        
        System.AssertEquals(LAC_CustomerController.getAvailableDoctorSpecialtyOptions(), specialities);
        System.AssertEquals(LAC_CustomerController.getAvailableDoctorGenderOptions(), genders);
        System.AssertEquals(LAC_CustomerController.getAvailableDoctorLanguageOptions(), languages);
        
        
        //LAC_CustomerController.CreateApp()
    }
}